name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login -u AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

    - name: Get ECR repository URI
      env:
        ECR_REPOSITORY_NAME: my-docker-repo     # specify the name of the repo same as in the variables.tf file
      id: ecr_uri
      run: |
        echo "::set-output name=ECR_REPO_URI::$(aws ecr describe-repositories --region $AWS_REGION --query 'repositories[?repositoryName==`${{ env.ECR_REPOSITORY_NAME }}`].repositoryUri' --output text)"    

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name my_beanstalk_app \
          --version-label $GITHUB_SHA \
          --source-bundle S3Bucket=$GITHUB_REPOSITORY,S3Key=$GITHUB_SHA.zip
        aws elasticbeanstalk update-environment \
          --application-name my_beanstalk_app \
          --environment-name my_beanstalk_env \
          --version-label $GITHUB_SHA

    - name: Deploy to EC2 Instances
      run: |
        # Use AWS CodeDeploy to deploy to EC2 instances
        aws deploy create-deployment \
          --application-name my-codedeploy-app \
          --deployment-group-name my-codedeploy-group \
          --s3-location bucket=$GITHUB_REPOSITORY,key=$GITHUB_SHA.zip

